
#Here are configs that need reloading to take effect
[general]
	#Enable Creative Tab
	creative_tab = false
	#Set to false to disable custom dispenser behaviors (i.e: filling jars) if for some reason they are causing trouble
	dispensers = true
	#Creates a creative tab full of filled jars
	jar_tab = false
	#Enables custom Configured config screen
	custom_configured_screen = true
	#The mod adds around 150 signs posts and hanging signs that are made with wood types from other mods (which make up the majority of registered blocks the mod adds).These are always registered and since they are so many could clutter up JEI and slow the game a bit. It's usually forge doesn't reccomend dynamically registering blocks but if you wish to enable such options you can here.With this option enabled the mod will on register the signs made from wood types of the currently installed mods
	conditional_sign_registration = true

[blocks]
	planter = true
	clock_block = true
	pedestal = true
	wind_vane = true
	redstone_illuminator = true
	notice_board = true
	crank = true
	jar = true
	jar_tinted = false
	faucet = true
	turn_table = true
	spring_launcher = true
	speaker_block = true
	sign_post = true
	hanging_sign = true
	bellows = true
	sconce = true
	sconce_green = false
	cage = true
	item_shelf = true
	sconce_lever = true
	cog_block = true
	globe = true
	hourglass = true
	sack = true
	blackboard = true
	safe = true
	copper_lantern = true
	flute = true
	gold_trapdoor = true
	gold_door = true
	bamboo_spikes = true
	bamboo_spikes_tipped = true
	stone_lamp = true
	end_stone_lamp = true
	blackstone_lamp = true
	deepslate_lamp = true
	checker_block = true
	netherite_door = true
	netherite_trapdoor = true
	pancake = true
	lock_block = true
	flax = true
	rope = true
	rope_arrow = true
	pulley_block = true
	fodder = true
	bomb = true
	crimson_lantern = true
	magma_cream_block = true
	daub = true
	wattle_and_daub = true
	timber_frame = true
	flag = true
	stone_tile = true
	goblet = true
	raked_gravel = true
	statue = true
	iron_gate = true
	feather_block = true
	flint_block = true
	slingshot = true
	shulker_shell = true
	candy = true
	wrench = true
	urn = true
	ash = true
	ash_bricks = true
	antique_ink = true
	doormat = true
	flower_box = true
	blackstone_tile = true
	soap = true
	bubble_blower = true
	globe_sepia = true
	#WIP
	present = true

